name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Do NOT use this template for support requests. If you have a question, please ask in the [Discussions](https://github.com/iSplasher/isomorphic-logger/discussions).
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: If you can, also include a clear and concise description of what you expected to happen.
      placeholder: A clear and concise description of what the issue is. Error stacktraces and screenshots are welcome!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package version
      description: What version of the package are you using?
      placeholder: ex. 1.0.0-alpha.2
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      description: What operating system are you using? Include OS version.
      placeholder: ex. Windows 10 21H1
  - type: input
    id: runtime
    attributes:
      label: Runtime
      description: Which runtime are you using? Include version.
      placeholder: ex. Node v18.2.1, Deno 1.0.1
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Which environment are you using the package in?
      placeholder: ex. Firefox 92.0, React Native
  - type: textarea
    id: details
    attributes:
      label: Additional details
      description: |
        Please copy and paste any relevant log or stacktrace output.
        This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Did you check for similar issues?
      description: Please check the [issue tracker](https://github.com/iSplasher/isomorphic-logger/issues) for similar issues.
      options:
        - label: I checked and didn't find similar issues.
          required: true
